// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MockDoer is an autogenerated mock type for the doer type
type MockDoer struct {
	mock.Mock
}

type MockDoer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDoer) EXPECT() *MockDoer_Expecter {
	return &MockDoer_Expecter{mock: &_m.Mock}
}

// Do provides a mock function with given fields: _a0
func (_m *MockDoer) Do(_a0 *http.Request) (*http.Response, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDoer_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockDoer_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - _a0 *http.Request
func (_e *MockDoer_Expecter) Do(_a0 interface{}) *MockDoer_Do_Call {
	return &MockDoer_Do_Call{Call: _e.mock.On("Do", _a0)}
}

func (_c *MockDoer_Do_Call) Run(run func(_a0 *http.Request)) *MockDoer_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*http.Request))
	})
	return _c
}

func (_c *MockDoer_Do_Call) Return(_a0 *http.Response, _a1 error) *MockDoer_Do_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDoer_Do_Call) RunAndReturn(run func(*http.Request) (*http.Response, error)) *MockDoer_Do_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDoer creates a new instance of MockDoer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDoer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDoer {
	mock := &MockDoer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
